language: generic 
sudo: required 
services:
 - docker

before_install:
 - docker build -t miguel787/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true miguel787/docker-react npm run test